### ISSUE TITLE
Instance XXX has been deleted.  Use the make_transient() function to send this object back to the transient state.

### ISSUE THREAD

**Issue by cancan101** [jeancochrane/pytest-flask-sqlalchemy#5] opened 2018-08-07 21:33 UTC
I added `db_session` to a view test that used to pass and it now fails with:

```
/Users/alex/.pyenv/versions/xxxx/lib/python3.7/site-packages/sqlalchemy/orm/session.py:2106: in _save_or_update_impl
    self._update_impl(state)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sqlalchemy.orm.session.SignallingSession object at 0x1105460b8>
state = <sqlalchemy.orm.state.InstanceState object at 0x1105e27f0>
revert_deletion = False

    def _update_impl(self, state, revert_deletion=False):
        if state.key is None:
            raise sa_exc.InvalidRequestError(
                "Instance '%s' is not persisted" %
                state_str(state))
    
        if state._deleted:
            if revert_deletion:
                if not state._attached:
                    return
                del state._deleted
            else:
                raise sa_exc.InvalidRequestError(
                    "Instance '%s' has been deleted.  "
                    "Use the make_transient() "
                    "function to send this object back "
                    "to the transient state." %
>                   state_str(state)
                )
E               sqlalchemy.exc.InvalidRequestError: Instance '<YYYY at 0x1105e28d0>' has been deleted.  Use the make_transient() function to send this object back to the transient state.

/Users/alex/.pyenv/versions/xxxx/lib/python3.7/site-packages/sqlalchemy/orm/session.py:2080: InvalidRequestError
```

**Comment by jeancochrane** [comment] 2018-08-08 00:50
Hmm, weird! Do you mind posting the failing test, the database/version you're using, and a `pip freeze`?

**Comment by cancan101** [comment] 2018-08-08 01:47
The issue is being caused by: https://github.com/jeancochrane/pytest-flask-sqlalchemy/blob/55eed1cb36bb3b510e84fd282056c3a455e4f853/pytest_flask_sqlalchemy/fixtures.py#L68

**Comment by jeancochrane** [comment] 2018-08-08 13:01
That line gets called in a few different contexts, since it's registered as an event listener on both `persistent_to_detached` and `deleted_to_detached`. I'm guessing the issue is with some cases of `deleted_to_detached`, but knowing the test context and the SQLAlchemy version you're using would help confirm that.

**Comment by cancan101** [comment] 2018-08-08 13:49
```
SQLAlchemy==1.2.10
Flask-SQLAlchemy==2.3.2
```
The test that is failing adds an association model to a collection in a view call and then removes and deletes that object using the `delete-orphan` behavior in another view calls.

eg.:
```python
child = Association()
m.children = [child]
...
m.children = []
```

**Comment by charness** [comment] 2018-09-13 16:40
I noticed an "optional step" in the `after_transaction_end` listener in the "Supporting Tests with Rollbacks" sidebar of SQLAlchemy's [Joining a Session into an External Transaction (such as for test suites)](http://docs.sqlalchemy.org/en/latest/orm/session_transaction.html#session-external-transaction) documentation:

``` python
                # ensure that state is expired the way
                # session.commit() at the top level normally does
                # (optional step)
                session.expire_all()
```

Adding that call at the corresponding spot in the `_transaction` fixture's `restart_savepoint` cleared up these errors in my test suite.

If I get a chance to develop a small test case that reproduces the error, I'll submit a PR. ("Works for me" doesn't feel rigorous enough for just adding the call, untested.) Meanwhile, that _seems_ to be the fix.

Many thanks for the plugin.

**Comment by jeancochrane** [comment] 2018-11-08 18:16
Should be closed via #6. Thanks for your work @charness! @cancan101 if this doesn't fix your problem, feel free to reopen with more diagnostics.

**Closed by jeancochrane** 2018-11-08 18:16 UTC
Labels: bug

**Comment by revmischa** [comment] 2019-05-15 11:14
I am getting the same error, deleting a model from an association table (in a flask request inside of a test) and the committing:

```python
myapp/api/playlist/admin/__init__.py:78: in update_playlist
    playlist.remove_all_videos()
myapp/model/playlist.py:52: in remove_all_videos
    db.session.commit()
../../../../.virtualenvs/myapp-pim5aQIP/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py:162: in do
    return getattr(self.registry(), name)(*args, **kwargs)
../../../../.virtualenvs/myapp-pim5aQIP/lib/python3.7/site-packages/sqlalchemy/orm/session.py:1026: in commit
    self.transaction.commit()
../../../../.virtualenvs/myapp-pim5aQIP/lib/python3.7/site-packages/sqlalchemy/orm/session.py:503: in commit
    self._remove_snapshot()
../../../../.virtualenvs/myapp-pim5aQIP/lib/python3.7/site-packages/sqlalchemy/orm/session.py:397: in _remove_snapshot
    list(self._deleted), self.session
../../../../.virtualenvs/myapp-pim5aQIP/lib/python3.7/site-packages/sqlalchemy/orm/state.py:361: in _detach_states
    deleted_to_detached(session, obj)
../../../../.virtualenvs/myapp-pim5aQIP/lib/python3.7/site-packages/sqlalchemy/event/attr.py:259: in __call__
    fn(*args, **kw)
../../../../.virtualenvs/myapp-pim5aQIP/lib/python3.7/site-packages/pytest_flask_sqlalchemy/fixtures.py:73: in rehydrate_object
    session.add(obj)
../../../../.virtualenvs/myapp-pim5aQIP/lib/python3.7/site-packages/sqlalchemy/orm/session.py:1947: in add
    self._save_or_update_state(state)
../../../../.virtualenvs/myapp-pim5aQIP/lib/python3.7/site-packages/sqlalchemy/orm/session.py:1960: in _save_or_update_state
    self._save_or_update_impl(state)
../../../../.virtualenvs/myapp-pim5aQIP/lib/python3.7/site-packages/sqlalchemy/orm/session.py:2303: in _save_or_update_impl
    self._update_impl(state)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sqlalchemy.orm.session.SignallingSession object at 0x1116062b0>, state = <sqlalchemy.orm.state.InstanceState object at 0x1116ae748>
revert_deletion = False

    def _update_impl(self, state, revert_deletion=False):
        if state.key is None:
            raise sa_exc.InvalidRequestError(
                "Instance '%s' is not persisted" % state_str(state)
            )
    
        if state._deleted:
            if revert_deletion:
                if not state._attached:
                    return
                del state._deleted
            else:
                raise sa_exc.InvalidRequestError(
                    "Instance '%s' has been deleted.  "
                    "Use the make_transient() "
                    "function to send this object back "
>                   "to the transient state." % state_str(state)
                )
E               sqlalchemy.exc.InvalidRequestError: Instance '<VideoPlaylist at 0x1116ae710>' has been deleted.  Use the make_transient() function to send this object back to the transient state.
```

Using version 1.0.2

**Comment by killthekitten** [comment] 2019-05-30 16:14
Same here

```pip
Flask-SQLAlchemy==2.3.2
pytest-flask-sqlalchemy==1.0.2
SQLAlchemy==1.2.19
SQLAlchemy-Continuum==1.3.9
SQLAlchemy-Utils==0.33.11
```

```python
def endpoint():
    data = request.get_json()
    model = MyModel.query.get(data["id"])
    db.session.delete(model)
    db.session.commit()
    return ...

def test_sign_in_with_one_time_code(api_client, db_session, user):
    model = Model.create_for(user)
    db_session.add(model)
    db_session.commit()

    response = api_client.post(
        "/endpoint", json={"id": model.id}
    )
    assert response.status_code == 200
```

**Comment by materemias** [comment] 2019-11-19 11:35
I experience the same with 
```
flask-sqlalchemy==2.4.1
pytest-flask-sqlalchemy==1.0.2
sqlalchemy==1.3.11
sqlalchemy-continuum==1.3.9
sqlalchemy-utils==0.35.0
```

**Comment by crawlchange** [comment] 2023-04-12 04:27
I also get this, but I'm only using the ORM. It seems to be impossible to delete children of a record.
